# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3e6edeb3153d364b30bd67ed3a1b2246a4fa3ac9f161f04ed526991ab38640515f63a7c929c1fe84d41e6d54627ac02b8352c988c005fc861f9d537f95dfc8

test:
  secret_key_base: dd5a6b6c8b949a20c39f20bf29d1846abf51c206ebcd85a9c2e1b6f4fbcff078c4d85de2c01192e1f0b4faa0f89cdf32b2e346fcc7edcefd9bfa451c9ed21419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
